topics:
  - name: auth-events
    partitions: 3
    replicationFactor: 1
    configs:
      retention.ms: 604800000 # 7 days
      
  - name: user-events
    partitions: 3
    replicationFactor: 1
    
  - name: notification-events
    partitions: 3
    replicationFactor: 1
